import * as http from "http";
import { AuditReport } from "@guardian/shared";

// Re-export new modules
export { SSEChannel } from "./sse/SSEChannel";
export { DashboardServer } from "./DashboardServer";
export {
  calculateHealthScore,
  calculateRadarData,
  calculateDashboardData,
} from "./calculations";
export type { DashboardData } from "./calculations";

// Server-side dashboard data shape (compatible with both old and new DashboardData)
export interface DashboardHtmlData {
  healthScore: number;
  totalFiles: number;
  totalLines: number;
  violations: {
    errors: number;
    warnings: number;
  };
  byAgent: Record<string, { errors: number; warnings: number }>;
  heatmap: Record<string, number | { violationCount: number }>;
}

function getHeatmapCount(value: number | { violationCount: number }): number {
  if (typeof value === "number") return value;
  return value.violationCount;
}

export function generateDashboardHtml(data: DashboardHtmlData): string {
  const agentRows = Object.entries(data.byAgent)
    .map(([name, counts]) => `<tr><td>${name}</td><td>${counts.errors}</td><td>${counts.warnings}</td></tr>`)
    .join("\n");

  const heatmapRows = Object.entries(data.heatmap)
    .sort((a, b) => getHeatmapCount(b[1]) - getHeatmapCount(a[1]))
    .map(([dir, value]) => {
      const count = getHeatmapCount(value);
      return `<tr><td>${dir}</td><td>${count}</td><td>${"\u2588".repeat(Math.min(count, 20))}</td></tr>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Guardian Dashboard</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; background: #1a1a2e; color: #eee; }
    .score { font-size: 4rem; font-weight: bold; text-align: center; color: ${data.healthScore >= 70 ? "#4caf50" : data.healthScore >= 40 ? "#ff9800" : "#f44336"}; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-top: 2rem; }
    .card { background: #16213e; border-radius: 12px; padding: 1.5rem; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #333; }
    th { color: #888; }
    h1, h2, h3 { color: #fff; }
    .subtitle { color: #888; text-align: center; }
  </style>
</head>
<body>
  <h1 style="text-align:center">Guardian Dashboard</h1>
  <p class="subtitle">Architecture Health Monitor</p>

  <div class="score">${data.healthScore}/100</div>
  <p class="subtitle">Health Score</p>

  <div class="grid">
    <div class="card">
      <h3>Summary</h3>
      <table>
        <tr><td>Total Files Analyzed</td><td>${data.totalFiles}</td></tr>
        <tr><td>Total Lines</td><td>${data.totalLines.toLocaleString()}</td></tr>
        <tr><td>Errors</td><td style="color:#f44336">${data.violations.errors}</td></tr>
        <tr><td>Warnings</td><td style="color:#ff9800">${data.violations.warnings}</td></tr>
      </table>
    </div>

    <div class="card">
      <h3>By Agent</h3>
      <table>
        <tr><th>Agent</th><th>Errors</th><th>Warnings</th></tr>
        ${agentRows}
      </table>
    </div>

    <div class="card" style="grid-column: span 2">
      <h3>Heatmap (Violation Density)</h3>
      <table>
        <tr><th>Directory</th><th>Violations</th><th>Density</th></tr>
        ${heatmapRows}
      </table>
    </div>
  </div>

  <p class="subtitle" style="margin-top:2rem">Generated by Guardian MCP Toolkit</p>
</body>
</html>`;
}

export function startDashboardServer(data: DashboardHtmlData, port: number = 3000): http.Server {
  const html = generateDashboardHtml(data);

  const server = http.createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
    res.end(html);
  });

  server.listen(port);
  return server;
}
